### ISSUE TITLE
Fix the code

### ISSUE THREAD

**Issue by iamrlz** [iamrlz/RPS-Game#4]
Changes needed:
- Score Tracking: Keep track of the scores for both the user and the computer across rounds.
- Game History: Display a history of moves, allowing users to see their previous choices and the computer's choices.
- Best of N Rounds: Allow users to set a specific number of rounds (like "Best of 5") at the start of the game.
- Enhanced Interface: Add more instructions and feedback to make it user-friendly.

Good Luck!

**Comment by rajalion442** [comment]
assign me!
